global:
  scrape_interval: 15s

scrape_configs:

  - job_name: 'node-exporters'
    static_configs:
      - targets:
          - 'node1:9100'
          - 'node2:9100'
          - 'main:9100'
          - 'prometheus:9100'

  - job_name: 'cadvisor'
    static_configs:
      - targets:
          - 'prometheus:8080'

  - job_name: 'elasticsearch'
    static_configs:
      - targets:
          - 'main:9114'

  - job_name: 'prometheus'
    static_configs:
      - targets:
          - 'prometheus:9090'

  - job_name: 'cognitive-deployer'
    static_configs:
      - targets:
          - 'main:8000'
          - 'node1:8000'
          - 'node2:8000'

  - job_name: 'dynamic-response'
    static_configs:
      - targets:
          - 'main:8001'
          - 'node1:8001'
          - 'node2:8001'
