# global is good node role = to manager may be an issue

version: "3.8"

services:
  elasticsearch:
    image: elasticsearch:7.17.18
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
      - honeynet

  logstash:
    image: logstash:7.17.18
    ports:
      - "5044:5044"
    configs:
      - source: logstash_conf
        target: /usr/share/logstash/pipeline/logstash.conf
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
      - honeynet

  kibana:
    image: kibana:7.17.18
    ports:
      - "5601:5601"
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
      - honeynet

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.18
    deploy:
      mode: global
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/hostname:/etc/nodename
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    networks:
      - honeynet

volumes:
  esdata:

configs:
  logstash_conf:
    file: ./logstash.conf

networks:
  honeynet:
    external: true
