filebeat.inputs:
  - type: container
    enabled: true
    paths:
      - /var/lib/docker/containers/*/*.log
    json.message_key: log
    json.keys_under_root: true
    processors:
      - add_docker_metadata: ~

output.logstash:
  hosts: ["elk_logstash:5044"]